# Generated by Django 5.2.8 on 2025-12-18 08:48

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='researchdata-files')),
                ('admin_notes', models.TextField(blank=True, help_text='Optional. Used for internal notes. Only visible on this page and will not appear on public website.', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='researchdata-resources')),
                ('video_youtube_id', models.CharField(blank=True, help_text="This can be found in the video URL. E.g. 'daUQPN5A2zA' in 'www.youtube.com/watch?v=daUQPN5A2zA'", max_length=20, null=True, verbose_name='Video (YouTube ID)')),
                ('url', models.URLField(blank=True, null=True)),
                ('request_feedback', models.BooleanField(default=False, help_text='Check to display feedback box from users for this resource')),
                ('published', models.BooleanField(default=True, help_text='Only published resources will appear on the public interface')),
                ('admin_notes', models.TextField(blank=True, help_text='Optional. Used for internal notes. Only visible on this page and will not appear on public website.', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': [django.db.models.functions.text.Upper('title'), 'id'],
            },
        ),
        migrations.CreateModel(
            name='ResourceStrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('navigation_link_name', models.CharField(max_length=255, unique=True)),
                ('navigation_link_order', models.IntegerField(default=0)),
                ('introduction', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('published', models.BooleanField(default=True, help_text='Only published resource strands will appear on the public interface')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': [django.db.models.functions.text.Upper('name'), 'id'],
            },
        ),
        migrations.CreateModel(
            name='ResourceFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('admin_notes', models.TextField(blank=True, help_text='Optional. Used for internal notes. Only visible on this page and will not appear on public website.', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='resource_feedbacks', to='researchdata.resource')),
            ],
            options={
                'verbose_name_plural': 'resource feedback',
            },
        ),
        migrations.AddField(
            model_name='resource',
            name='strand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='resources', to='researchdata.resourcestrand'),
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='researchdata-stories')),
                ('video_youtube_id', models.CharField(blank=True, help_text="This can be found in the video URL. E.g. 'daUQPN5A2zA' in 'www.youtube.com/watch?v=daUQPN5A2zA'", max_length=20, null=True, verbose_name='Video (YouTube ID)')),
                ('author_name', models.CharField(blank=True, max_length=200, null=True)),
                ('author_name_show', models.BooleanField(default=True, help_text="Ticking this box will show the author's name on the public interface")),
                ('published', models.BooleanField(default=True, help_text='Only published stories will appear on the public interface')),
                ('admin_notes', models.TextField(blank=True, help_text='Optional. Used for internal notes. Only visible on this page and will not appear on public website.', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='stories', to='researchdata.storygroup')),
            ],
            options={
                'verbose_name_plural': 'stories',
                'ordering': [django.db.models.functions.text.Upper('title'), 'id'],
            },
        ),
    ]
