# Generated by Django 5.2.8 on 2026-02-17 09:25

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchdata', '0002_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': [django.db.models.functions.text.Upper('name'), 'id'],
            },
        ),
        migrations.AddField(
            model_name='story',
            name='image_show',
            field=models.BooleanField(default=True, help_text='Ticking this box will show the image at the top of the story, unticking will hide it. The image will always be shown as the thumbnail in the list of stories'),
        ),
        migrations.AddField(
            model_name='story',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='researchdata.storytype'),
        ),
    ]
